version: '3.4'

services:
  portfolio:
    container_name: ovi_portofolio_container
    build: 
      context: .
      dockerfile: .dockerfile
    user: "1000"
    environment: 
      - mlabURI=${mlabURI}
      - JWTSecret=${JWTSecret}
      - EmailToUserName=${EmailToUserName}
      - EmailUserName=${EmailUserName}
      - EmailPassword=${EmailPassword}
      - EmailFromUserName=${EmailFromUserName}
      - BASE_URI=${BASE_URI}
      - IGNORE_LOCATIONS=${IGNORE_LOCATIONS}
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - portfolio_network 
    environment:
      - PORT=3000
    ports:
      - 3000:3000

networks: 
  portfolio_network:

volumes:
  node_modules: