version: '3'

services:
  portfolio:
    container_name: ovi_portofolio_container
    build: 
      context: .
      dockerfile: .dockerfile
    volumes:
       - .:/app
    networks: 
      - portfolio_network 
    environment:
      - PORT=3000
    ports:
      - 3000:3000

networks: 
  portfolio_network: